# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup node 12.x
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 12.x

      # Installs pnpm globally
      - name: Install pnpm
        run: npm i -g pnpm

      # Installs dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Runs a build
      - name: Build
        run: pnpm build

      # Runs tests
      - name: Run tests
        run: pnpm test:unit
